"""
This type stub file was generated by pyright.
"""

"""Provides utility functions"""
def seconds_to_years(seconds):
    """Convert seconds to years"""
    ...

def years_to_seconds(years): # -> int:
    """Convert years to seconds"""
    ...

def seconds_to_months(seconds):
    """Convert seconds to months"""
    ...

def months_to_seconds(months): # -> int:
    """Convert months to seconds"""
    ...

def seconds_to_weeks(seconds):
    """Convert seconds to weeks"""
    ...

def weeks_to_seconds(weeks): # -> int:
    """Convert weeks to seconds"""
    ...

def seconds_to_days(seconds):
    """Convert seconds to days"""
    ...

def days_to_seconds(days): # -> int:
    """Convert days to seconds"""
    ...

def params_to_dict(method_name, args, kwargs):
    """Given args and kwargs, return a dictionary object"""
    ...

def params_to_list(args): # -> list[Any]:
    """Convert a list of arguments (some of which may be lists) to a flat list"""
    ...

def to_ref(obj): # -> Any:
    """Convert a file or container to a reference"""
    ...

def set_verify_ssl(session): # -> None:
    """Create a session that verifies against correct certs"""
    ...

def check_filename_params(params): # -> None:
    """Check filename parameters for invalid characters"""
    ...

