"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class AnalysisOutputInflatedJob:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, id=..., label=..., parent=..., parents=..., created=..., modified=..., revision=..., inputs=..., description=..., info=..., files=..., notes=..., tags=..., job_id=..., job=..., gear_info=..., compute_provider_id=..., join_origin=..., copy_of=..., original_copy_of=...) -> None:
        """AnalysisOutputInflatedJob - a model defined in Swagger"""
        ...
    
    @property
    def id(self): # -> None:
        """Gets the id of this AnalysisOutputInflatedJob.


        :return: The id of this AnalysisOutputInflatedJob.
        :rtype: str
        """
        ...
    
    @id.setter
    def id(self, id): # -> None:
        """Sets the id of this AnalysisOutputInflatedJob.


        :param id: The id of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def label(self): # -> None:
        """Gets the label of this AnalysisOutputInflatedJob.


        :return: The label of this AnalysisOutputInflatedJob.
        :rtype: str
        """
        ...
    
    @label.setter
    def label(self, label): # -> None:
        """Sets the label of this AnalysisOutputInflatedJob.


        :param label: The label of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def parent(self): # -> None:
        """Gets the parent of this AnalysisOutputInflatedJob.


        :return: The parent of this AnalysisOutputInflatedJob.
        :rtype: ContainerReference
        """
        ...
    
    @parent.setter
    def parent(self, parent): # -> None:
        """Sets the parent of this AnalysisOutputInflatedJob.


        :param parent: The parent of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: ContainerReference
        """
        ...
    
    @property
    def parents(self): # -> None:
        """Gets the parents of this AnalysisOutputInflatedJob.


        :return: The parents of this AnalysisOutputInflatedJob.
        :rtype: AnalysisParents
        """
        ...
    
    @parents.setter
    def parents(self, parents): # -> None:
        """Sets the parents of this AnalysisOutputInflatedJob.


        :param parents: The parents of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: AnalysisParents
        """
        ...
    
    @property
    def created(self): # -> None:
        """Gets the created of this AnalysisOutputInflatedJob.


        :return: The created of this AnalysisOutputInflatedJob.
        :rtype: datetime
        """
        ...
    
    @created.setter
    def created(self, created): # -> None:
        """Sets the created of this AnalysisOutputInflatedJob.


        :param created: The created of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def modified(self): # -> None:
        """Gets the modified of this AnalysisOutputInflatedJob.


        :return: The modified of this AnalysisOutputInflatedJob.
        :rtype: datetime
        """
        ...
    
    @modified.setter
    def modified(self, modified): # -> None:
        """Sets the modified of this AnalysisOutputInflatedJob.


        :param modified: The modified of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def revision(self): # -> None:
        """Gets the revision of this AnalysisOutputInflatedJob.


        :return: The revision of this AnalysisOutputInflatedJob.
        :rtype: int
        """
        ...
    
    @revision.setter
    def revision(self, revision): # -> None:
        """Sets the revision of this AnalysisOutputInflatedJob.


        :param revision: The revision of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def inputs(self): # -> None:
        """Gets the inputs of this AnalysisOutputInflatedJob.


        :return: The inputs of this AnalysisOutputInflatedJob.
        :rtype: list[FileOutput]
        """
        ...
    
    @inputs.setter
    def inputs(self, inputs): # -> None:
        """Sets the inputs of this AnalysisOutputInflatedJob.


        :param inputs: The inputs of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: list[FileOutput]
        """
        ...
    
    @property
    def description(self): # -> None:
        """Gets the description of this AnalysisOutputInflatedJob.


        :return: The description of this AnalysisOutputInflatedJob.
        :rtype: str
        """
        ...
    
    @description.setter
    def description(self, description): # -> None:
        """Sets the description of this AnalysisOutputInflatedJob.


        :param description: The description of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def info(self): # -> None:
        """Gets the info of this AnalysisOutputInflatedJob.


        :return: The info of this AnalysisOutputInflatedJob.
        :rtype: object
        """
        ...
    
    @info.setter
    def info(self, info): # -> None:
        """Sets the info of this AnalysisOutputInflatedJob.


        :param info: The info of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: object
        """
        ...
    
    @property
    def files(self): # -> None:
        """Gets the files of this AnalysisOutputInflatedJob.


        :return: The files of this AnalysisOutputInflatedJob.
        :rtype: list[FileOutput]
        """
        ...
    
    @files.setter
    def files(self, files): # -> None:
        """Sets the files of this AnalysisOutputInflatedJob.


        :param files: The files of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: list[FileOutput]
        """
        ...
    
    @property
    def notes(self): # -> None:
        """Gets the notes of this AnalysisOutputInflatedJob.


        :return: The notes of this AnalysisOutputInflatedJob.
        :rtype: list[Note]
        """
        ...
    
    @notes.setter
    def notes(self, notes): # -> None:
        """Sets the notes of this AnalysisOutputInflatedJob.


        :param notes: The notes of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: list[Note]
        """
        ...
    
    @property
    def tags(self): # -> None:
        """Gets the tags of this AnalysisOutputInflatedJob.


        :return: The tags of this AnalysisOutputInflatedJob.
        :rtype: list[str]
        """
        ...
    
    @tags.setter
    def tags(self, tags): # -> None:
        """Sets the tags of this AnalysisOutputInflatedJob.


        :param tags: The tags of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def job_id(self): # -> None:
        """Gets the job_id of this AnalysisOutputInflatedJob.


        :return: The job_id of this AnalysisOutputInflatedJob.
        :rtype: str
        """
        ...
    
    @job_id.setter
    def job_id(self, job_id): # -> None:
        """Sets the job_id of this AnalysisOutputInflatedJob.


        :param job_id: The job_id of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def job(self): # -> None:
        """Gets the job of this AnalysisOutputInflatedJob.


        :return: The job of this AnalysisOutputInflatedJob.
        :rtype: JobOutput
        """
        ...
    
    @job.setter
    def job(self, job): # -> None:
        """Sets the job of this AnalysisOutputInflatedJob.


        :param job: The job of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: JobOutput
        """
        ...
    
    @property
    def gear_info(self): # -> None:
        """Gets the gear_info of this AnalysisOutputInflatedJob.


        :return: The gear_info of this AnalysisOutputInflatedJob.
        :rtype: GearInfo
        """
        ...
    
    @gear_info.setter
    def gear_info(self, gear_info): # -> None:
        """Sets the gear_info of this AnalysisOutputInflatedJob.


        :param gear_info: The gear_info of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: GearInfo
        """
        ...
    
    @property
    def compute_provider_id(self): # -> None:
        """Gets the compute_provider_id of this AnalysisOutputInflatedJob.


        :return: The compute_provider_id of this AnalysisOutputInflatedJob.
        :rtype: str
        """
        ...
    
    @compute_provider_id.setter
    def compute_provider_id(self, compute_provider_id): # -> None:
        """Sets the compute_provider_id of this AnalysisOutputInflatedJob.


        :param compute_provider_id: The compute_provider_id of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def join_origin(self): # -> None:
        """Gets the join_origin of this AnalysisOutputInflatedJob.


        :return: The join_origin of this AnalysisOutputInflatedJob.
        :rtype: JoinOrigins
        """
        ...
    
    @join_origin.setter
    def join_origin(self, join_origin): # -> None:
        """Sets the join_origin of this AnalysisOutputInflatedJob.


        :param join_origin: The join_origin of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: JoinOrigins
        """
        ...
    
    @property
    def copy_of(self): # -> None:
        """Gets the copy_of of this AnalysisOutputInflatedJob.


        :return: The copy_of of this AnalysisOutputInflatedJob.
        :rtype: str
        """
        ...
    
    @copy_of.setter
    def copy_of(self, copy_of): # -> None:
        """Sets the copy_of of this AnalysisOutputInflatedJob.


        :param copy_of: The copy_of of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def original_copy_of(self): # -> None:
        """Gets the original_copy_of of this AnalysisOutputInflatedJob.


        :return: The original_copy_of of this AnalysisOutputInflatedJob.
        :rtype: str
        """
        ...
    
    @original_copy_of.setter
    def original_copy_of(self, original_copy_of): # -> None:
        """Sets the original_copy_of of this AnalysisOutputInflatedJob.


        :param original_copy_of: The original_copy_of of this AnalysisOutputInflatedJob.  # noqa: E501
        :type: str
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


