"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class AsStorage:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, bucket=..., path=..., signed_urls=..., region=..., config_type=..., config_class=...) -> None:
        """AsStorage - a model defined in Swagger"""
        ...
    
    @property
    def bucket(self): # -> None:
        """Gets the bucket of this AsStorage.


        :return: The bucket of this AsStorage.
        :rtype: str
        """
        ...
    
    @bucket.setter
    def bucket(self, bucket): # -> None:
        """Sets the bucket of this AsStorage.


        :param bucket: The bucket of this AsStorage.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def path(self): # -> None:
        """Gets the path of this AsStorage.


        :return: The path of this AsStorage.
        :rtype: str
        """
        ...
    
    @path.setter
    def path(self, path): # -> None:
        """Sets the path of this AsStorage.


        :param path: The path of this AsStorage.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def signed_urls(self): # -> None:
        """Gets the signed_urls of this AsStorage.


        :return: The signed_urls of this AsStorage.
        :rtype: bool
        """
        ...
    
    @signed_urls.setter
    def signed_urls(self, signed_urls): # -> None:
        """Sets the signed_urls of this AsStorage.


        :param signed_urls: The signed_urls of this AsStorage.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def region(self): # -> None:
        """Gets the region of this AsStorage.


        :return: The region of this AsStorage.
        :rtype: str
        """
        ...
    
    @region.setter
    def region(self, region): # -> None:
        """Sets the region of this AsStorage.


        :param region: The region of this AsStorage.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def config_type(self): # -> None:
        """Gets the config_type of this AsStorage.


        :return: The config_type of this AsStorage.
        :rtype: str
        """
        ...
    
    @config_type.setter
    def config_type(self, config_type): # -> None:
        """Sets the config_type of this AsStorage.


        :param config_type: The config_type of this AsStorage.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def config_class(self): # -> None:
        """Gets the config_class of this AsStorage.


        :return: The config_class of this AsStorage.
        :rtype: str
        """
        ...
    
    @config_class.setter
    def config_class(self, config_class): # -> None:
        """Sets the config_class of this AsStorage.


        :param config_class: The config_class of this AsStorage.  # noqa: E501
        :type: str
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


