"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class ConfigOut:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, last_updated=..., site=..., features=..., wip_features=..., signed_url=..., auth=..., created=..., modified=..., central=...) -> None:
        """ConfigOut - a model defined in Swagger"""
        ...
    
    @property
    def last_updated(self): # -> None:
        """Gets the last_updated of this ConfigOut.


        :return: The last_updated of this ConfigOut.
        :rtype: datetime
        """
        ...
    
    @last_updated.setter
    def last_updated(self, last_updated): # -> None:
        """Sets the last_updated of this ConfigOut.


        :param last_updated: The last_updated of this ConfigOut.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def site(self): # -> None:
        """Gets the site of this ConfigOut.


        :return: The site of this ConfigOut.
        :rtype: Site
        """
        ...
    
    @site.setter
    def site(self, site): # -> None:
        """Sets the site of this ConfigOut.


        :param site: The site of this ConfigOut.  # noqa: E501
        :type: Site
        """
        ...
    
    @property
    def features(self): # -> None:
        """Gets the features of this ConfigOut.


        :return: The features of this ConfigOut.
        :rtype: Features
        """
        ...
    
    @features.setter
    def features(self, features): # -> None:
        """Sets the features of this ConfigOut.


        :param features: The features of this ConfigOut.  # noqa: E501
        :type: Features
        """
        ...
    
    @property
    def wip_features(self): # -> None:
        """Gets the wip_features of this ConfigOut.


        :return: The wip_features of this ConfigOut.
        :rtype: WorkInProgressFeatures
        """
        ...
    
    @wip_features.setter
    def wip_features(self, wip_features): # -> None:
        """Sets the wip_features of this ConfigOut.


        :param wip_features: The wip_features of this ConfigOut.  # noqa: E501
        :type: WorkInProgressFeatures
        """
        ...
    
    @property
    def signed_url(self): # -> None:
        """Gets the signed_url of this ConfigOut.


        :return: The signed_url of this ConfigOut.
        :rtype: bool
        """
        ...
    
    @signed_url.setter
    def signed_url(self, signed_url): # -> None:
        """Sets the signed_url of this ConfigOut.


        :param signed_url: The signed_url of this ConfigOut.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def auth(self): # -> None:
        """Gets the auth of this ConfigOut.


        :return: The auth of this ConfigOut.
        :rtype: AuthOut
        """
        ...
    
    @auth.setter
    def auth(self, auth): # -> None:
        """Sets the auth of this ConfigOut.


        :param auth: The auth of this ConfigOut.  # noqa: E501
        :type: AuthOut
        """
        ...
    
    @property
    def created(self): # -> None:
        """Gets the created of this ConfigOut.


        :return: The created of this ConfigOut.
        :rtype: datetime
        """
        ...
    
    @created.setter
    def created(self, created): # -> None:
        """Sets the created of this ConfigOut.


        :param created: The created of this ConfigOut.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def modified(self): # -> None:
        """Gets the modified of this ConfigOut.


        :return: The modified of this ConfigOut.
        :rtype: datetime
        """
        ...
    
    @modified.setter
    def modified(self, modified): # -> None:
        """Sets the modified of this ConfigOut.


        :param modified: The modified of this ConfigOut.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def central(self): # -> None:
        """Gets the central of this ConfigOut.


        :return: The central of this ConfigOut.
        :rtype: CentralOut
        """
        ...
    
    @central.setter
    def central(self, central): # -> None:
        """Sets the central of this ConfigOut.


        :param central: The central of this ConfigOut.  # noqa: E501
        :type: CentralOut
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


