"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class ContainerFilter:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, type=..., tags=...) -> None:
        """ContainerFilter - a model defined in Swagger"""
        ...
    
    @property
    def type(self): # -> None:
        """Gets the type of this ContainerFilter.


        :return: The type of this ContainerFilter.
        :rtype: ContainerType
        """
        ...
    
    @type.setter
    def type(self, type): # -> None:
        """Sets the type of this ContainerFilter.


        :param type: The type of this ContainerFilter.  # noqa: E501
        :type: ContainerType
        """
        ...
    
    @property
    def tags(self): # -> None:
        """Gets the tags of this ContainerFilter.


        :return: The tags of this ContainerFilter.
        :rtype: FilterValues
        """
        ...
    
    @tags.setter
    def tags(self, tags): # -> None:
        """Sets the tags of this ContainerFilter.


        :param tags: The tags of this ContainerFilter.  # noqa: E501
        :type: FilterValues
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


