"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class DeviceSelfUpdate:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, type=..., version=..., interval=..., errors=..., info=...) -> None:
        """DeviceSelfUpdate - a model defined in Swagger"""
        ...
    
    @property
    def type(self): # -> None:
        """Gets the type of this DeviceSelfUpdate.


        :return: The type of this DeviceSelfUpdate.
        :rtype: str
        """
        ...
    
    @type.setter
    def type(self, type): # -> None:
        """Sets the type of this DeviceSelfUpdate.


        :param type: The type of this DeviceSelfUpdate.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def version(self): # -> None:
        """Gets the version of this DeviceSelfUpdate.


        :return: The version of this DeviceSelfUpdate.
        :rtype: str
        """
        ...
    
    @version.setter
    def version(self, version): # -> None:
        """Sets the version of this DeviceSelfUpdate.


        :param version: The version of this DeviceSelfUpdate.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def interval(self): # -> None:
        """Gets the interval of this DeviceSelfUpdate.


        :return: The interval of this DeviceSelfUpdate.
        :rtype: int
        """
        ...
    
    @interval.setter
    def interval(self, interval): # -> None:
        """Sets the interval of this DeviceSelfUpdate.


        :param interval: The interval of this DeviceSelfUpdate.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def errors(self): # -> None:
        """Gets the errors of this DeviceSelfUpdate.


        :return: The errors of this DeviceSelfUpdate.
        :rtype: list[str]
        """
        ...
    
    @errors.setter
    def errors(self, errors): # -> None:
        """Sets the errors of this DeviceSelfUpdate.


        :param errors: The errors of this DeviceSelfUpdate.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def info(self): # -> None:
        """Gets the info of this DeviceSelfUpdate.


        :return: The info of this DeviceSelfUpdate.
        :rtype: object
        """
        ...
    
    @info.setter
    def info(self, info): # -> None:
        """Sets the info of this DeviceSelfUpdate.


        :param info: The info of this DeviceSelfUpdate.  # noqa: E501
        :type: object
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


