"""
This type stub file was generated by pyright.
"""

from .mixins import FileMixin

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class FileNode(FileMixin):
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, id=..., name=..., type=..., mimetype=..., file_id=..., version=..., modality=..., deid_log_id=..., deid_log_skip_reason=..., classification=..., tags=..., provider_id=..., path=..., reference=..., restored_from=..., restored_by=..., parent_ref=..., parents=..., origin=..., virus_scan=..., created=..., modified=..., replaced=..., deleted=..., size=..., hash=..., info=..., info_exists=..., cvat=..., zip_member_count=..., gear_info=..., copy_of=..., original_copy_of=..., revision=..., file_group=..., client_hash=...) -> None:
        """FileNode - a model defined in Swagger"""
        ...
    
    @property
    def id(self): # -> None:
        """Gets the id of this FileNode.


        :return: The id of this FileNode.
        :rtype: str
        """
        ...
    
    @id.setter
    def id(self, id): # -> None:
        """Sets the id of this FileNode.


        :param id: The id of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def name(self): # -> None:
        """Gets the name of this FileNode.


        :return: The name of this FileNode.
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """Sets the name of this FileNode.


        :param name: The name of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def type(self): # -> None:
        """Gets the type of this FileNode.


        :return: The type of this FileNode.
        :rtype: str
        """
        ...
    
    @type.setter
    def type(self, type): # -> None:
        """Sets the type of this FileNode.


        :param type: The type of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def mimetype(self): # -> None:
        """Gets the mimetype of this FileNode.


        :return: The mimetype of this FileNode.
        :rtype: str
        """
        ...
    
    @mimetype.setter
    def mimetype(self, mimetype): # -> None:
        """Sets the mimetype of this FileNode.


        :param mimetype: The mimetype of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def file_id(self): # -> None:
        """Gets the file_id of this FileNode.


        :return: The file_id of this FileNode.
        :rtype: str
        """
        ...
    
    @file_id.setter
    def file_id(self, file_id): # -> None:
        """Sets the file_id of this FileNode.


        :param file_id: The file_id of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def version(self): # -> None:
        """Gets the version of this FileNode.


        :return: The version of this FileNode.
        :rtype: int
        """
        ...
    
    @version.setter
    def version(self, version): # -> None:
        """Sets the version of this FileNode.


        :param version: The version of this FileNode.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def modality(self): # -> None:
        """Gets the modality of this FileNode.


        :return: The modality of this FileNode.
        :rtype: str
        """
        ...
    
    @modality.setter
    def modality(self, modality): # -> None:
        """Sets the modality of this FileNode.


        :param modality: The modality of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def deid_log_id(self): # -> None:
        """Gets the deid_log_id of this FileNode.


        :return: The deid_log_id of this FileNode.
        :rtype: str
        """
        ...
    
    @deid_log_id.setter
    def deid_log_id(self, deid_log_id): # -> None:
        """Sets the deid_log_id of this FileNode.


        :param deid_log_id: The deid_log_id of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def deid_log_skip_reason(self): # -> None:
        """Gets the deid_log_skip_reason of this FileNode.


        :return: The deid_log_skip_reason of this FileNode.
        :rtype: DeidLogSkipReason
        """
        ...
    
    @deid_log_skip_reason.setter
    def deid_log_skip_reason(self, deid_log_skip_reason): # -> None:
        """Sets the deid_log_skip_reason of this FileNode.


        :param deid_log_skip_reason: The deid_log_skip_reason of this FileNode.  # noqa: E501
        :type: DeidLogSkipReason
        """
        ...
    
    @property
    def classification(self): # -> None:
        """Gets the classification of this FileNode.


        :return: The classification of this FileNode.
        :rtype: dict(str, list[str])
        """
        ...
    
    @classification.setter
    def classification(self, classification): # -> None:
        """Sets the classification of this FileNode.


        :param classification: The classification of this FileNode.  # noqa: E501
        :type: dict(str, list[str])
        """
        ...
    
    @property
    def tags(self): # -> None:
        """Gets the tags of this FileNode.


        :return: The tags of this FileNode.
        :rtype: list[str]
        """
        ...
    
    @tags.setter
    def tags(self, tags): # -> None:
        """Sets the tags of this FileNode.


        :param tags: The tags of this FileNode.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def provider_id(self): # -> None:
        """Gets the provider_id of this FileNode.


        :return: The provider_id of this FileNode.
        :rtype: str
        """
        ...
    
    @provider_id.setter
    def provider_id(self, provider_id): # -> None:
        """Sets the provider_id of this FileNode.


        :param provider_id: The provider_id of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def path(self): # -> None:
        """Gets the path of this FileNode.


        :return: The path of this FileNode.
        :rtype: str
        """
        ...
    
    @path.setter
    def path(self, path): # -> None:
        """Sets the path of this FileNode.


        :param path: The path of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def reference(self): # -> None:
        """Gets the reference of this FileNode.


        :return: The reference of this FileNode.
        :rtype: bool
        """
        ...
    
    @reference.setter
    def reference(self, reference): # -> None:
        """Sets the reference of this FileNode.


        :param reference: The reference of this FileNode.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def restored_from(self): # -> None:
        """Gets the restored_from of this FileNode.


        :return: The restored_from of this FileNode.
        :rtype: int
        """
        ...
    
    @restored_from.setter
    def restored_from(self, restored_from): # -> None:
        """Sets the restored_from of this FileNode.


        :param restored_from: The restored_from of this FileNode.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def restored_by(self): # -> None:
        """Gets the restored_by of this FileNode.


        :return: The restored_by of this FileNode.
        :rtype: Origin
        """
        ...
    
    @restored_by.setter
    def restored_by(self, restored_by): # -> None:
        """Sets the restored_by of this FileNode.


        :param restored_by: The restored_by of this FileNode.  # noqa: E501
        :type: Origin
        """
        ...
    
    @property
    def parent_ref(self): # -> None:
        """Gets the parent_ref of this FileNode.


        :return: The parent_ref of this FileNode.
        :rtype: ContainerReference
        """
        ...
    
    @parent_ref.setter
    def parent_ref(self, parent_ref): # -> None:
        """Sets the parent_ref of this FileNode.


        :param parent_ref: The parent_ref of this FileNode.  # noqa: E501
        :type: ContainerReference
        """
        ...
    
    @property
    def parents(self): # -> None:
        """Gets the parents of this FileNode.


        :return: The parents of this FileNode.
        :rtype: FileParents
        """
        ...
    
    @parents.setter
    def parents(self, parents): # -> None:
        """Sets the parents of this FileNode.


        :param parents: The parents of this FileNode.  # noqa: E501
        :type: FileParents
        """
        ...
    
    @property
    def origin(self): # -> None:
        """Gets the origin of this FileNode.


        :return: The origin of this FileNode.
        :rtype: Origin
        """
        ...
    
    @origin.setter
    def origin(self, origin): # -> None:
        """Sets the origin of this FileNode.


        :param origin: The origin of this FileNode.  # noqa: E501
        :type: Origin
        """
        ...
    
    @property
    def virus_scan(self): # -> None:
        """Gets the virus_scan of this FileNode.


        :return: The virus_scan of this FileNode.
        :rtype: VirusScan
        """
        ...
    
    @virus_scan.setter
    def virus_scan(self, virus_scan): # -> None:
        """Sets the virus_scan of this FileNode.


        :param virus_scan: The virus_scan of this FileNode.  # noqa: E501
        :type: VirusScan
        """
        ...
    
    @property
    def created(self): # -> None:
        """Gets the created of this FileNode.


        :return: The created of this FileNode.
        :rtype: datetime
        """
        ...
    
    @created.setter
    def created(self, created): # -> None:
        """Sets the created of this FileNode.


        :param created: The created of this FileNode.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def modified(self): # -> None:
        """Gets the modified of this FileNode.


        :return: The modified of this FileNode.
        :rtype: datetime
        """
        ...
    
    @modified.setter
    def modified(self, modified): # -> None:
        """Sets the modified of this FileNode.


        :param modified: The modified of this FileNode.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def replaced(self): # -> None:
        """Gets the replaced of this FileNode.


        :return: The replaced of this FileNode.
        :rtype: datetime
        """
        ...
    
    @replaced.setter
    def replaced(self, replaced): # -> None:
        """Sets the replaced of this FileNode.


        :param replaced: The replaced of this FileNode.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def deleted(self): # -> None:
        """Gets the deleted of this FileNode.


        :return: The deleted of this FileNode.
        :rtype: datetime
        """
        ...
    
    @deleted.setter
    def deleted(self, deleted): # -> None:
        """Sets the deleted of this FileNode.


        :param deleted: The deleted of this FileNode.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def size(self): # -> None:
        """Gets the size of this FileNode.


        :return: The size of this FileNode.
        :rtype: int
        """
        ...
    
    @size.setter
    def size(self, size): # -> None:
        """Sets the size of this FileNode.


        :param size: The size of this FileNode.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def hash(self): # -> None:
        """Gets the hash of this FileNode.


        :return: The hash of this FileNode.
        :rtype: str
        """
        ...
    
    @hash.setter
    def hash(self, hash): # -> None:
        """Sets the hash of this FileNode.


        :param hash: The hash of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def info(self): # -> None:
        """Gets the info of this FileNode.


        :return: The info of this FileNode.
        :rtype: object
        """
        ...
    
    @info.setter
    def info(self, info): # -> None:
        """Sets the info of this FileNode.


        :param info: The info of this FileNode.  # noqa: E501
        :type: object
        """
        ...
    
    @property
    def info_exists(self): # -> None:
        """Gets the info_exists of this FileNode.


        :return: The info_exists of this FileNode.
        :rtype: bool
        """
        ...
    
    @info_exists.setter
    def info_exists(self, info_exists): # -> None:
        """Sets the info_exists of this FileNode.


        :param info_exists: The info_exists of this FileNode.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def cvat(self): # -> None:
        """Gets the cvat of this FileNode.


        :return: The cvat of this FileNode.
        :rtype: CVATInfo
        """
        ...
    
    @cvat.setter
    def cvat(self, cvat): # -> None:
        """Sets the cvat of this FileNode.


        :param cvat: The cvat of this FileNode.  # noqa: E501
        :type: CVATInfo
        """
        ...
    
    @property
    def zip_member_count(self): # -> None:
        """Gets the zip_member_count of this FileNode.


        :return: The zip_member_count of this FileNode.
        :rtype: int
        """
        ...
    
    @zip_member_count.setter
    def zip_member_count(self, zip_member_count): # -> None:
        """Sets the zip_member_count of this FileNode.


        :param zip_member_count: The zip_member_count of this FileNode.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def gear_info(self): # -> None:
        """Gets the gear_info of this FileNode.


        :return: The gear_info of this FileNode.
        :rtype: FileGearInfo
        """
        ...
    
    @gear_info.setter
    def gear_info(self, gear_info): # -> None:
        """Sets the gear_info of this FileNode.


        :param gear_info: The gear_info of this FileNode.  # noqa: E501
        :type: FileGearInfo
        """
        ...
    
    @property
    def copy_of(self): # -> None:
        """Gets the copy_of of this FileNode.


        :return: The copy_of of this FileNode.
        :rtype: FileVersionCopyOf
        """
        ...
    
    @copy_of.setter
    def copy_of(self, copy_of): # -> None:
        """Sets the copy_of of this FileNode.


        :param copy_of: The copy_of of this FileNode.  # noqa: E501
        :type: FileVersionCopyOf
        """
        ...
    
    @property
    def original_copy_of(self): # -> None:
        """Gets the original_copy_of of this FileNode.


        :return: The original_copy_of of this FileNode.
        :rtype: FileVersion
        """
        ...
    
    @original_copy_of.setter
    def original_copy_of(self, original_copy_of): # -> None:
        """Sets the original_copy_of of this FileNode.


        :param original_copy_of: The original_copy_of of this FileNode.  # noqa: E501
        :type: FileVersion
        """
        ...
    
    @property
    def revision(self): # -> None:
        """Gets the revision of this FileNode.


        :return: The revision of this FileNode.
        :rtype: int
        """
        ...
    
    @revision.setter
    def revision(self, revision): # -> None:
        """Sets the revision of this FileNode.


        :param revision: The revision of this FileNode.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def file_group(self): # -> None:
        """Gets the file_group of this FileNode.


        :return: The file_group of this FileNode.
        :rtype: FileGroup
        """
        ...
    
    @file_group.setter
    def file_group(self, file_group): # -> None:
        """Sets the file_group of this FileNode.


        :param file_group: The file_group of this FileNode.  # noqa: E501
        :type: FileGroup
        """
        ...
    
    @property
    def client_hash(self): # -> None:
        """Gets the client_hash of this FileNode.


        :return: The client_hash of this FileNode.
        :rtype: str
        """
        ...
    
    @client_hash.setter
    def client_hash(self, client_hash): # -> None:
        """Sets the client_hash of this FileNode.


        :param client_hash: The client_hash of this FileNode.  # noqa: E501
        :type: str
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


