"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class FileVersionOutput:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, created=..., deleted=..., file_id=..., origin=..., restored_from=..., restored_by=..., version=...) -> None:
        """FileVersionOutput - a model defined in Swagger"""
        ...
    
    @property
    def created(self): # -> None:
        """Gets the created of this FileVersionOutput.


        :return: The created of this FileVersionOutput.
        :rtype: datetime
        """
        ...
    
    @created.setter
    def created(self, created): # -> None:
        """Sets the created of this FileVersionOutput.


        :param created: The created of this FileVersionOutput.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def deleted(self): # -> None:
        """Gets the deleted of this FileVersionOutput.


        :return: The deleted of this FileVersionOutput.
        :rtype: datetime
        """
        ...
    
    @deleted.setter
    def deleted(self, deleted): # -> None:
        """Sets the deleted of this FileVersionOutput.


        :param deleted: The deleted of this FileVersionOutput.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def file_id(self): # -> None:
        """Gets the file_id of this FileVersionOutput.


        :return: The file_id of this FileVersionOutput.
        :rtype: str
        """
        ...
    
    @file_id.setter
    def file_id(self, file_id): # -> None:
        """Sets the file_id of this FileVersionOutput.


        :param file_id: The file_id of this FileVersionOutput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def origin(self): # -> None:
        """Gets the origin of this FileVersionOutput.


        :return: The origin of this FileVersionOutput.
        :rtype: Origin
        """
        ...
    
    @origin.setter
    def origin(self, origin): # -> None:
        """Sets the origin of this FileVersionOutput.


        :param origin: The origin of this FileVersionOutput.  # noqa: E501
        :type: Origin
        """
        ...
    
    @property
    def restored_from(self): # -> None:
        """Gets the restored_from of this FileVersionOutput.


        :return: The restored_from of this FileVersionOutput.
        :rtype: int
        """
        ...
    
    @restored_from.setter
    def restored_from(self, restored_from): # -> None:
        """Sets the restored_from of this FileVersionOutput.


        :param restored_from: The restored_from of this FileVersionOutput.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def restored_by(self): # -> None:
        """Gets the restored_by of this FileVersionOutput.


        :return: The restored_by of this FileVersionOutput.
        :rtype: Origin
        """
        ...
    
    @restored_by.setter
    def restored_by(self, restored_by): # -> None:
        """Sets the restored_by of this FileVersionOutput.


        :param restored_by: The restored_by of this FileVersionOutput.  # noqa: E501
        :type: Origin
        """
        ...
    
    @property
    def version(self): # -> None:
        """Gets the version of this FileVersionOutput.


        :return: The version of this FileVersionOutput.
        :rtype: int
        """
        ...
    
    @version.setter
    def version(self, version): # -> None:
        """Sets the version of this FileVersionOutput.


        :param version: The version of this FileVersionOutput.  # noqa: E501
        :type: int
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


