"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class FileUpsertInput:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, provider_id=..., uuid=..., path=..., reference=..., client_hash=..., name=..., size=..., type=..., mimetype=..., modality=..., classification=..., info=..., zip_member_count=..., tags=..., parent_ref=..., origin=..., source=...) -> None:
        """FileUpsertInput - a model defined in Swagger"""
        ...
    
    @property
    def provider_id(self): # -> None:
        """Gets the provider_id of this FileUpsertInput.

        Unique database ID

        :return: The provider_id of this FileUpsertInput.
        :rtype: str
        """
        ...
    
    @provider_id.setter
    def provider_id(self, provider_id): # -> None:
        """Sets the provider_id of this FileUpsertInput.

        Unique database ID

        :param provider_id: The provider_id of this FileUpsertInput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def uuid(self): # -> None:
        """Gets the uuid of this FileUpsertInput.

        Hyphen-separated universally unique identifier

        :return: The uuid of this FileUpsertInput.
        :rtype: str
        """
        ...
    
    @uuid.setter
    def uuid(self, uuid): # -> None:
        """Sets the uuid of this FileUpsertInput.

        Hyphen-separated universally unique identifier

        :param uuid: The uuid of this FileUpsertInput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def path(self): # -> None:
        """Gets the path of this FileUpsertInput.


        :return: The path of this FileUpsertInput.
        :rtype: str
        """
        ...
    
    @path.setter
    def path(self, path): # -> None:
        """Sets the path of this FileUpsertInput.


        :param path: The path of this FileUpsertInput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def reference(self): # -> None:
        """Gets the reference of this FileUpsertInput.


        :return: The reference of this FileUpsertInput.
        :rtype: bool
        """
        ...
    
    @reference.setter
    def reference(self, reference): # -> None:
        """Sets the reference of this FileUpsertInput.


        :param reference: The reference of this FileUpsertInput.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def client_hash(self): # -> None:
        """Gets the client_hash of this FileUpsertInput.


        :return: The client_hash of this FileUpsertInput.
        :rtype: str
        """
        ...
    
    @client_hash.setter
    def client_hash(self, client_hash): # -> None:
        """Sets the client_hash of this FileUpsertInput.


        :param client_hash: The client_hash of this FileUpsertInput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def name(self): # -> None:
        """Gets the name of this FileUpsertInput.

        The name of the file on disk

        :return: The name of this FileUpsertInput.
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """Sets the name of this FileUpsertInput.

        The name of the file on disk

        :param name: The name of this FileUpsertInput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def size(self): # -> None:
        """Gets the size of this FileUpsertInput.


        :return: The size of this FileUpsertInput.
        :rtype: int
        """
        ...
    
    @size.setter
    def size(self, size): # -> None:
        """Sets the size of this FileUpsertInput.


        :param size: The size of this FileUpsertInput.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def type(self): # -> None:
        """Gets the type of this FileUpsertInput.

        A descriptive file type (e.g. dicom, image, document, ...)

        :return: The type of this FileUpsertInput.
        :rtype: str
        """
        ...
    
    @type.setter
    def type(self, type): # -> None:
        """Sets the type of this FileUpsertInput.

        A descriptive file type (e.g. dicom, image, document, ...)

        :param type: The type of this FileUpsertInput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def mimetype(self): # -> None:
        """Gets the mimetype of this FileUpsertInput.

        A MIME Content-Type of the file

        :return: The mimetype of this FileUpsertInput.
        :rtype: str
        """
        ...
    
    @mimetype.setter
    def mimetype(self, mimetype): # -> None:
        """Sets the mimetype of this FileUpsertInput.

        A MIME Content-Type of the file

        :param mimetype: The mimetype of this FileUpsertInput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def modality(self): # -> None:
        """Gets the modality of this FileUpsertInput.

        The type of instrument that originated the file (e.g. MR, CT, ...)

        :return: The modality of this FileUpsertInput.
        :rtype: str
        """
        ...
    
    @modality.setter
    def modality(self, modality): # -> None:
        """Sets the modality of this FileUpsertInput.

        The type of instrument that originated the file (e.g. MR, CT, ...)

        :param modality: The modality of this FileUpsertInput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def classification(self): # -> None:
        """Gets the classification of this FileUpsertInput.


        :return: The classification of this FileUpsertInput.
        :rtype: dict(str, list[str])
        """
        ...
    
    @classification.setter
    def classification(self, classification): # -> None:
        """Sets the classification of this FileUpsertInput.


        :param classification: The classification of this FileUpsertInput.  # noqa: E501
        :type: dict(str, list[str])
        """
        ...
    
    @property
    def info(self): # -> None:
        """Gets the info of this FileUpsertInput.

        Free-form information storage

        :return: The info of this FileUpsertInput.
        :rtype: object
        """
        ...
    
    @info.setter
    def info(self, info): # -> None:
        """Sets the info of this FileUpsertInput.

        Free-form information storage

        :param info: The info of this FileUpsertInput.  # noqa: E501
        :type: object
        """
        ...
    
    @property
    def zip_member_count(self): # -> None:
        """Gets the zip_member_count of this FileUpsertInput.

        Number of entries in the zip archive

        :return: The zip_member_count of this FileUpsertInput.
        :rtype: int
        """
        ...
    
    @zip_member_count.setter
    def zip_member_count(self, zip_member_count): # -> None:
        """Sets the zip_member_count of this FileUpsertInput.

        Number of entries in the zip archive

        :param zip_member_count: The zip_member_count of this FileUpsertInput.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def tags(self): # -> None:
        """Gets the tags of this FileUpsertInput.


        :return: The tags of this FileUpsertInput.
        :rtype: list[str]
        """
        ...
    
    @tags.setter
    def tags(self, tags): # -> None:
        """Sets the tags of this FileUpsertInput.


        :param tags: The tags of this FileUpsertInput.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def parent_ref(self): # -> None:
        """Gets the parent_ref of this FileUpsertInput.


        :return: The parent_ref of this FileUpsertInput.
        :rtype: ContainerReference
        """
        ...
    
    @parent_ref.setter
    def parent_ref(self, parent_ref): # -> None:
        """Sets the parent_ref of this FileUpsertInput.


        :param parent_ref: The parent_ref of this FileUpsertInput.  # noqa: E501
        :type: ContainerReference
        """
        ...
    
    @property
    def origin(self): # -> None:
        """Gets the origin of this FileUpsertInput.


        :return: The origin of this FileUpsertInput.
        :rtype: Origin
        """
        ...
    
    @origin.setter
    def origin(self, origin): # -> None:
        """Sets the origin of this FileUpsertInput.


        :param origin: The origin of this FileUpsertInput.  # noqa: E501
        :type: Origin
        """
        ...
    
    @property
    def source(self): # -> None:
        """Gets the source of this FileUpsertInput.


        :return: The source of this FileUpsertInput.
        :rtype: CoreModelsCommonSource
        """
        ...
    
    @source.setter
    def source(self, source): # -> None:
        """Sets the source of this FileUpsertInput.


        :param source: The source of this FileUpsertInput.  # noqa: E501
        :type: CoreModelsCommonSource
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


