"""
This type stub file was generated by pyright.
"""

from flywheel.models.origin import Origin

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class FileUpsertOrigin(Origin):
    """This model is deprecated and will be removed in a future release.
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    


