"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class GearExchange:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, git_commit=..., rootfs_hash=..., rootfs_url=...) -> None:
        """GearExchange - a model defined in Swagger"""
        ...
    
    @property
    def git_commit(self): # -> None:
        """Gets the git_commit of this GearExchange.

        The SHA-1 hash referring to the git commit

        :return: The git_commit of this GearExchange.
        :rtype: str
        """
        ...
    
    @git_commit.setter
    def git_commit(self, git_commit): # -> None:
        """Sets the git_commit of this GearExchange.

        The SHA-1 hash referring to the git commit

        :param git_commit: The git_commit of this GearExchange.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def rootfs_hash(self): # -> None:
        """Gets the rootfs_hash of this GearExchange.

        The cryptographic hash of the root filesystem in the form of \"algorithm:<base16 hash>\"

        :return: The rootfs_hash of this GearExchange.
        :rtype: str
        """
        ...
    
    @rootfs_hash.setter
    def rootfs_hash(self, rootfs_hash): # -> None:
        """Sets the rootfs_hash of this GearExchange.

        The cryptographic hash of the root filesystem in the form of \"algorithm:<base16 hash>\"

        :param rootfs_hash: The rootfs_hash of this GearExchange.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def rootfs_url(self): # -> None:
        """Gets the rootfs_url of this GearExchange.

        The absolute URL of the gear's root file system

        :return: The rootfs_url of this GearExchange.
        :rtype: str
        """
        ...
    
    @rootfs_url.setter
    def rootfs_url(self, rootfs_url): # -> None:
        """Sets the rootfs_url of this GearExchange.

        The absolute URL of the gear's root file system

        :param rootfs_url: The rootfs_url of this GearExchange.  # noqa: E501
        :type: str
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


