"""
This type stub file was generated by pyright.
"""

"""Provides gear invocation support"""
class GearInvocation:
    """Represents the details necessary to execute a gear as a job"""
    def __init__(self, gear) -> None:
        ...
    
    def update_config(self, *args, **kwargs): # -> None:
        """Update configuration values"""
        ...
    
    def set_analysis_label(self, label): # -> None:
        """Set the analysis label, if executing an analysis gear"""
        ...
    
    def add_tag(self, tag): # -> None:
        """Add a tag to the job"""
        ...
    
    def add_tags(self, tags): # -> None:
        """Add multiple tags to the job"""
        ...
    
    def set_input(self, key, input): # -> None:
        """Add an input"""
        ...
    
    def set_destination(self, dest): # -> None:
        """Set the destination container"""
        ...
    
    def set_priority(self, priority): # -> None:
        """Set the priority of gear job"""
        ...
    
    def run(self): # -> Any:
        """Run the invocation as a single job (or analysis).

        Requires that required inputs and the destination have been set.

        Returns the job id, or the analysis id in the case of an analysis gear.
        """
        ...
    
    def propose_batch(self, containers, optional_input_policy=...):
        """Create a batch run proposal for the given containers

        :param list containers: The list of containers to run the job on
        :param str optional_input_policy: The optional input policy (default is ignored)
        """
        ...
    


