"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class GearContextValueOutput:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, container_type=..., label=..., id=..., value=..., found=...) -> None:
        """GearContextValueOutput - a model defined in Swagger"""
        ...
    
    @property
    def container_type(self): # -> None:
        """Gets the container_type of this GearContextValueOutput.


        :return: The container_type of this GearContextValueOutput.
        :rtype: ContainerType
        """
        ...
    
    @container_type.setter
    def container_type(self, container_type): # -> None:
        """Sets the container_type of this GearContextValueOutput.


        :param container_type: The container_type of this GearContextValueOutput.  # noqa: E501
        :type: ContainerType
        """
        ...
    
    @property
    def label(self): # -> None:
        """Gets the label of this GearContextValueOutput.


        :return: The label of this GearContextValueOutput.
        :rtype: str
        """
        ...
    
    @label.setter
    def label(self, label): # -> None:
        """Sets the label of this GearContextValueOutput.


        :param label: The label of this GearContextValueOutput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def id(self): # -> None:
        """Gets the id of this GearContextValueOutput.


        :return: The id of this GearContextValueOutput.
        :rtype: str
        """
        ...
    
    @id.setter
    def id(self, id): # -> None:
        """Sets the id of this GearContextValueOutput.


        :param id: The id of this GearContextValueOutput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def value(self): # -> None:
        """Gets the value of this GearContextValueOutput.


        :return: The value of this GearContextValueOutput.
        :rtype: object
        """
        ...
    
    @value.setter
    def value(self, value): # -> None:
        """Sets the value of this GearContextValueOutput.


        :param value: The value of this GearContextValueOutput.  # noqa: E501
        :type: object
        """
        ...
    
    @property
    def found(self): # -> None:
        """Gets the found of this GearContextValueOutput.


        :return: The found of this GearContextValueOutput.
        :rtype: bool
        """
        ...
    
    @found.setter
    def found(self, found): # -> None:
        """Sets the found of this GearContextValueOutput.


        :param found: The found of this GearContextValueOutput.  # noqa: E501
        :type: bool
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


