"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class GearDocumentInput:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, category=..., gear=..., exchange=..., created=..., modified=..., disabled=...) -> None:
        """GearDocumentInput - a model defined in Swagger"""
        ...
    
    @property
    def category(self): # -> None:
        """Gets the category of this GearDocumentInput.


        :return: The category of this GearDocumentInput.
        :rtype: GearCategory
        """
        ...
    
    @category.setter
    def category(self, category): # -> None:
        """Sets the category of this GearDocumentInput.


        :param category: The category of this GearDocumentInput.  # noqa: E501
        :type: GearCategory
        """
        ...
    
    @property
    def gear(self): # -> None:
        """Gets the gear of this GearDocumentInput.


        :return: The gear of this GearDocumentInput.
        :rtype: GearManifest
        """
        ...
    
    @gear.setter
    def gear(self, gear): # -> None:
        """Sets the gear of this GearDocumentInput.


        :param gear: The gear of this GearDocumentInput.  # noqa: E501
        :type: GearManifest
        """
        ...
    
    @property
    def exchange(self): # -> None:
        """Gets the exchange of this GearDocumentInput.


        :return: The exchange of this GearDocumentInput.
        :rtype: GearExchange
        """
        ...
    
    @exchange.setter
    def exchange(self, exchange): # -> None:
        """Sets the exchange of this GearDocumentInput.


        :param exchange: The exchange of this GearDocumentInput.  # noqa: E501
        :type: GearExchange
        """
        ...
    
    @property
    def created(self): # -> None:
        """Gets the created of this GearDocumentInput.


        :return: The created of this GearDocumentInput.
        :rtype: datetime
        """
        ...
    
    @created.setter
    def created(self, created): # -> None:
        """Sets the created of this GearDocumentInput.


        :param created: The created of this GearDocumentInput.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def modified(self): # -> None:
        """Gets the modified of this GearDocumentInput.


        :return: The modified of this GearDocumentInput.
        :rtype: datetime
        """
        ...
    
    @modified.setter
    def modified(self, modified): # -> None:
        """Sets the modified of this GearDocumentInput.


        :param modified: The modified of this GearDocumentInput.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def disabled(self): # -> None:
        """Gets the disabled of this GearDocumentInput.


        :return: The disabled of this GearDocumentInput.
        :rtype: datetime
        """
        ...
    
    @disabled.setter
    def disabled(self, disabled): # -> None:
        """Sets the disabled of this GearDocumentInput.


        :param disabled: The disabled of this GearDocumentInput.  # noqa: E501
        :type: datetime
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


