"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class GraphFilter:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, groups=..., projects=..., subjects=..., sessions=..., acquisitions=..., analyses=..., jobs=...) -> None:
        """GraphFilter - a model defined in Swagger"""
        ...
    
    @property
    def groups(self): # -> None:
        """Gets the groups of this GraphFilter.


        :return: The groups of this GraphFilter.
        :rtype: TreeContainerRequestSpec
        """
        ...
    
    @groups.setter
    def groups(self, groups): # -> None:
        """Sets the groups of this GraphFilter.


        :param groups: The groups of this GraphFilter.  # noqa: E501
        :type: TreeContainerRequestSpec
        """
        ...
    
    @property
    def projects(self): # -> None:
        """Gets the projects of this GraphFilter.


        :return: The projects of this GraphFilter.
        :rtype: TreeContainerRequestSpec
        """
        ...
    
    @projects.setter
    def projects(self, projects): # -> None:
        """Sets the projects of this GraphFilter.


        :param projects: The projects of this GraphFilter.  # noqa: E501
        :type: TreeContainerRequestSpec
        """
        ...
    
    @property
    def subjects(self): # -> None:
        """Gets the subjects of this GraphFilter.


        :return: The subjects of this GraphFilter.
        :rtype: TreeContainerRequestSpec
        """
        ...
    
    @subjects.setter
    def subjects(self, subjects): # -> None:
        """Sets the subjects of this GraphFilter.


        :param subjects: The subjects of this GraphFilter.  # noqa: E501
        :type: TreeContainerRequestSpec
        """
        ...
    
    @property
    def sessions(self): # -> None:
        """Gets the sessions of this GraphFilter.


        :return: The sessions of this GraphFilter.
        :rtype: TreeContainerRequestSpec
        """
        ...
    
    @sessions.setter
    def sessions(self, sessions): # -> None:
        """Sets the sessions of this GraphFilter.


        :param sessions: The sessions of this GraphFilter.  # noqa: E501
        :type: TreeContainerRequestSpec
        """
        ...
    
    @property
    def acquisitions(self): # -> None:
        """Gets the acquisitions of this GraphFilter.


        :return: The acquisitions of this GraphFilter.
        :rtype: TreeContainerRequestSpec
        """
        ...
    
    @acquisitions.setter
    def acquisitions(self, acquisitions): # -> None:
        """Sets the acquisitions of this GraphFilter.


        :param acquisitions: The acquisitions of this GraphFilter.  # noqa: E501
        :type: TreeContainerRequestSpec
        """
        ...
    
    @property
    def analyses(self): # -> None:
        """Gets the analyses of this GraphFilter.


        :return: The analyses of this GraphFilter.
        :rtype: TreeContainerRequestSpec
        """
        ...
    
    @analyses.setter
    def analyses(self, analyses): # -> None:
        """Sets the analyses of this GraphFilter.


        :param analyses: The analyses of this GraphFilter.  # noqa: E501
        :type: TreeContainerRequestSpec
        """
        ...
    
    @property
    def jobs(self): # -> None:
        """Gets the jobs of this GraphFilter.


        :return: The jobs of this GraphFilter.
        :rtype: TreeContainerRequestSpec
        """
        ...
    
    @jobs.setter
    def jobs(self, jobs): # -> None:
        """Sets the jobs of this GraphFilter.


        :param jobs: The jobs of this GraphFilter.  # noqa: E501
        :type: TreeContainerRequestSpec
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


