"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class GroupUpdate:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, label=..., providers=..., editions=..., modified=...) -> None:
        """GroupUpdate - a model defined in Swagger"""
        ...
    
    @property
    def label(self): # -> None:
        """Gets the label of this GroupUpdate.


        :return: The label of this GroupUpdate.
        :rtype: str
        """
        ...
    
    @label.setter
    def label(self, label): # -> None:
        """Sets the label of this GroupUpdate.


        :param label: The label of this GroupUpdate.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def providers(self): # -> None:
        """Gets the providers of this GroupUpdate.


        :return: The providers of this GroupUpdate.
        :rtype: Providers
        """
        ...
    
    @providers.setter
    def providers(self, providers): # -> None:
        """Sets the providers of this GroupUpdate.


        :param providers: The providers of this GroupUpdate.  # noqa: E501
        :type: Providers
        """
        ...
    
    @property
    def editions(self): # -> None:
        """Gets the editions of this GroupUpdate.


        :return: The editions of this GroupUpdate.
        :rtype: Edition
        """
        ...
    
    @editions.setter
    def editions(self, editions): # -> None:
        """Sets the editions of this GroupUpdate.


        :param editions: The editions of this GroupUpdate.  # noqa: E501
        :type: Edition
        """
        ...
    
    @property
    def modified(self): # -> None:
        """Gets the modified of this GroupUpdate.


        :return: The modified of this GroupUpdate.
        :rtype: datetime
        """
        ...
    
    @modified.setter
    def modified(self, modified): # -> None:
        """Sets the modified of this GroupUpdate.


        :param modified: The modified of this GroupUpdate.  # noqa: E501
        :type: datetime
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


