"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class JobComplete:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, success=..., failure_reason=..., profile=...) -> None:
        """JobComplete - a model defined in Swagger"""
        ...
    
    @property
    def success(self): # -> None:
        """Gets the success of this JobComplete.


        :return: The success of this JobComplete.
        :rtype: bool
        """
        ...
    
    @success.setter
    def success(self, success): # -> None:
        """Sets the success of this JobComplete.


        :param success: The success of this JobComplete.  # noqa: E501
        :type: bool
        """
        ...
    
    @property
    def failure_reason(self): # -> None:
        """Gets the failure_reason of this JobComplete.


        :return: The failure_reason of this JobComplete.
        :rtype: str
        """
        ...
    
    @failure_reason.setter
    def failure_reason(self, failure_reason): # -> None:
        """Sets the failure_reason of this JobComplete.


        :param failure_reason: The failure_reason of this JobComplete.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def profile(self): # -> None:
        """Gets the profile of this JobComplete.


        :return: The profile of this JobComplete.
        :rtype: InputJobProfile
        """
        ...
    
    @profile.setter
    def profile(self, profile): # -> None:
        """Sets the profile of this JobComplete.


        :param profile: The profile of this JobComplete.  # noqa: E501
        :type: InputJobProfile
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


