"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class JobConfigInput:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, group=..., gear_name=..., tag=..., compute_provider=..., created_by=...) -> None:
        """JobConfigInput - a model defined in Swagger"""
        ...
    
    @property
    def group(self): # -> None:
        """Gets the group of this JobConfigInput.


        :return: The group of this JobConfigInput.
        :rtype: list[str]
        """
        ...
    
    @group.setter
    def group(self, group): # -> None:
        """Sets the group of this JobConfigInput.


        :param group: The group of this JobConfigInput.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def gear_name(self): # -> None:
        """Gets the gear_name of this JobConfigInput.


        :return: The gear_name of this JobConfigInput.
        :rtype: list[str]
        """
        ...
    
    @gear_name.setter
    def gear_name(self, gear_name): # -> None:
        """Sets the gear_name of this JobConfigInput.


        :param gear_name: The gear_name of this JobConfigInput.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def tag(self): # -> None:
        """Gets the tag of this JobConfigInput.


        :return: The tag of this JobConfigInput.
        :rtype: list[str]
        """
        ...
    
    @tag.setter
    def tag(self, tag): # -> None:
        """Sets the tag of this JobConfigInput.


        :param tag: The tag of this JobConfigInput.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def compute_provider(self): # -> None:
        """Gets the compute_provider of this JobConfigInput.


        :return: The compute_provider of this JobConfigInput.
        :rtype: list[str]
        """
        ...
    
    @compute_provider.setter
    def compute_provider(self, compute_provider): # -> None:
        """Sets the compute_provider of this JobConfigInput.


        :param compute_provider: The compute_provider of this JobConfigInput.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @property
    def created_by(self): # -> None:
        """Gets the created_by of this JobConfigInput.


        :return: The created_by of this JobConfigInput.
        :rtype: list[str]
        """
        ...
    
    @created_by.setter
    def created_by(self, created_by): # -> None:
        """Sets the created_by of this JobConfigInput.


        :param created_by: The created_by of this JobConfigInput.  # noqa: E501
        :type: list[str]
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


