"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class JobTransitionTimes:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, running=..., failed=..., complete=..., cancelled=...) -> None:
        """JobTransitionTimes - a model defined in Swagger"""
        ...
    
    @property
    def running(self): # -> None:
        """Gets the running of this JobTransitionTimes.

        The timestamp when the job transitioned into the running state

        :return: The running of this JobTransitionTimes.
        :rtype: datetime
        """
        ...
    
    @running.setter
    def running(self, running): # -> None:
        """Sets the running of this JobTransitionTimes.

        The timestamp when the job transitioned into the running state

        :param running: The running of this JobTransitionTimes.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def failed(self): # -> None:
        """Gets the failed of this JobTransitionTimes.

        The timestamp when the job transitioned into the failed state

        :return: The failed of this JobTransitionTimes.
        :rtype: datetime
        """
        ...
    
    @failed.setter
    def failed(self, failed): # -> None:
        """Sets the failed of this JobTransitionTimes.

        The timestamp when the job transitioned into the failed state

        :param failed: The failed of this JobTransitionTimes.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def complete(self): # -> None:
        """Gets the complete of this JobTransitionTimes.

        The timestamp when the job transitioned into the complete state

        :return: The complete of this JobTransitionTimes.
        :rtype: datetime
        """
        ...
    
    @complete.setter
    def complete(self, complete): # -> None:
        """Sets the complete of this JobTransitionTimes.

        The timestamp when the job transitioned into the complete state

        :param complete: The complete of this JobTransitionTimes.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def cancelled(self): # -> None:
        """Gets the cancelled of this JobTransitionTimes.

        The timestamp when the job transitioned into the cancelled state

        :return: The cancelled of this JobTransitionTimes.
        :rtype: datetime
        """
        ...
    
    @cancelled.setter
    def cancelled(self, cancelled): # -> None:
        """Sets the cancelled of this JobTransitionTimes.

        The timestamp when the job transitioned into the cancelled state

        :param cancelled: The cancelled of this JobTransitionTimes.  # noqa: E501
        :type: datetime
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


