"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class JobFileInputListOutput:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, hierarchy=..., object=..., location=..., base=...) -> None:
        """JobFileInputListOutput - a model defined in Swagger"""
        ...
    
    @property
    def hierarchy(self): # -> None:
        """Gets the hierarchy of this JobFileInputListOutput.


        :return: The hierarchy of this JobFileInputListOutput.
        :rtype: ContainerReference
        """
        ...
    
    @hierarchy.setter
    def hierarchy(self, hierarchy): # -> None:
        """Sets the hierarchy of this JobFileInputListOutput.


        :param hierarchy: The hierarchy of this JobFileInputListOutput.  # noqa: E501
        :type: ContainerReference
        """
        ...
    
    @property
    def object(self): # -> None:
        """Gets the object of this JobFileInputListOutput.


        :return: The object of this JobFileInputListOutput.
        :rtype: JobFileObjectListOutput
        """
        ...
    
    @object.setter
    def object(self, object): # -> None:
        """Sets the object of this JobFileInputListOutput.


        :param object: The object of this JobFileInputListOutput.  # noqa: E501
        :type: JobFileObjectListOutput
        """
        ...
    
    @property
    def location(self): # -> None:
        """Gets the location of this JobFileInputListOutput.


        :return: The location of this JobFileInputListOutput.
        :rtype: Location
        """
        ...
    
    @location.setter
    def location(self, location): # -> None:
        """Sets the location of this JobFileInputListOutput.


        :param location: The location of this JobFileInputListOutput.  # noqa: E501
        :type: Location
        """
        ...
    
    @property
    def base(self): # -> None:
        """Gets the base of this JobFileInputListOutput.


        :return: The base of this JobFileInputListOutput.
        :rtype: str
        """
        ...
    
    @base.setter
    def base(self, base): # -> None:
        """Sets the base of this JobFileInputListOutput.


        :param base: The base of this JobFileInputListOutput.  # noqa: E501
        :type: str
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


