"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class JupyterlabServerModify:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, label=..., last_modified_by=..., deleted=..., external_storage_id=..., latest_version=...) -> None:
        """JupyterlabServerModify - a model defined in Swagger"""
        ...
    
    @property
    def label(self): # -> None:
        """Gets the label of this JupyterlabServerModify.


        :return: The label of this JupyterlabServerModify.
        :rtype: str
        """
        ...
    
    @label.setter
    def label(self, label): # -> None:
        """Sets the label of this JupyterlabServerModify.


        :param label: The label of this JupyterlabServerModify.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def last_modified_by(self): # -> None:
        """Gets the last_modified_by of this JupyterlabServerModify.


        :return: The last_modified_by of this JupyterlabServerModify.
        :rtype: Origin
        """
        ...
    
    @last_modified_by.setter
    def last_modified_by(self, last_modified_by): # -> None:
        """Sets the last_modified_by of this JupyterlabServerModify.


        :param last_modified_by: The last_modified_by of this JupyterlabServerModify.  # noqa: E501
        :type: Origin
        """
        ...
    
    @property
    def deleted(self): # -> None:
        """Gets the deleted of this JupyterlabServerModify.


        :return: The deleted of this JupyterlabServerModify.
        :rtype: datetime
        """
        ...
    
    @deleted.setter
    def deleted(self, deleted): # -> None:
        """Sets the deleted of this JupyterlabServerModify.


        :param deleted: The deleted of this JupyterlabServerModify.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def external_storage_id(self): # -> None:
        """Gets the external_storage_id of this JupyterlabServerModify.


        :return: The external_storage_id of this JupyterlabServerModify.
        :rtype: str
        """
        ...
    
    @external_storage_id.setter
    def external_storage_id(self, external_storage_id): # -> None:
        """Sets the external_storage_id of this JupyterlabServerModify.


        :param external_storage_id: The external_storage_id of this JupyterlabServerModify.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def latest_version(self): # -> None:
        """Gets the latest_version of this JupyterlabServerModify.


        :return: The latest_version of this JupyterlabServerModify.
        :rtype: int
        """
        ...
    
    @latest_version.setter
    def latest_version(self, latest_version): # -> None:
        """Sets the latest_version of this JupyterlabServerModify.


        :param latest_version: The latest_version of this JupyterlabServerModify.  # noqa: E501
        :type: int
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


