"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class LegacyUsageReport:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, gear_execution_count=..., file_mbs=..., session_count=..., year=..., month=..., project=...) -> None:
        """LegacyUsageReport - a model defined in Swagger"""
        ...
    
    @property
    def gear_execution_count(self): # -> None:
        """Gets the gear_execution_count of this LegacyUsageReport.

        The number of gears executed

        :return: The gear_execution_count of this LegacyUsageReport.
        :rtype: int
        """
        ...
    
    @gear_execution_count.setter
    def gear_execution_count(self, gear_execution_count): # -> None:
        """Sets the gear_execution_count of this LegacyUsageReport.

        The number of gears executed

        :param gear_execution_count: The gear_execution_count of this LegacyUsageReport.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def file_mbs(self): # -> None:
        """Gets the file_mbs of this LegacyUsageReport.

        File storage usage, in megabytes

        :return: The file_mbs of this LegacyUsageReport.
        :rtype: float
        """
        ...
    
    @file_mbs.setter
    def file_mbs(self, file_mbs): # -> None:
        """Sets the file_mbs of this LegacyUsageReport.

        File storage usage, in megabytes

        :param file_mbs: The file_mbs of this LegacyUsageReport.  # noqa: E501
        :type: float
        """
        ...
    
    @property
    def session_count(self): # -> None:
        """Gets the session_count of this LegacyUsageReport.

        The number of sessions created

        :return: The session_count of this LegacyUsageReport.
        :rtype: int
        """
        ...
    
    @session_count.setter
    def session_count(self, session_count): # -> None:
        """Sets the session_count of this LegacyUsageReport.

        The number of sessions created

        :param session_count: The session_count of this LegacyUsageReport.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def year(self): # -> None:
        """Gets the year of this LegacyUsageReport.

        The year portion of the entry date

        :return: The year of this LegacyUsageReport.
        :rtype: str
        """
        ...
    
    @year.setter
    def year(self, year): # -> None:
        """Sets the year of this LegacyUsageReport.

        The year portion of the entry date

        :param year: The year of this LegacyUsageReport.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def month(self): # -> None:
        """Gets the month of this LegacyUsageReport.

        The month portion of the entry date

        :return: The month of this LegacyUsageReport.
        :rtype: str
        """
        ...
    
    @month.setter
    def month(self, month): # -> None:
        """Sets the month of this LegacyUsageReport.

        The month portion of the entry date

        :param month: The month of this LegacyUsageReport.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def project(self): # -> None:
        """Gets the project of this LegacyUsageReport.


        :return: The project of this LegacyUsageReport.
        :rtype: LegacysUsageProjectEntry
        """
        ...
    
    @project.setter
    def project(self, project): # -> None:
        """Sets the project of this LegacyUsageReport.


        :param project: The project of this LegacyUsageReport.  # noqa: E501
        :type: LegacysUsageProjectEntry
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


