"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class Note:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, id=..., created=..., modified=..., timestamp=..., firstname=..., lastname=..., text=..., user=..., avatar=...) -> None:
        """Note - a model defined in Swagger"""
        ...
    
    @property
    def id(self): # -> None:
        """Gets the id of this Note.

        Unique database ID

        :return: The id of this Note.
        :rtype: str
        """
        ...
    
    @id.setter
    def id(self, id): # -> None:
        """Sets the id of this Note.

        Unique database ID

        :param id: The id of this Note.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def created(self): # -> None:
        """Gets the created of this Note.

        Creation time (automatically set)

        :return: The created of this Note.
        :rtype: datetime
        """
        ...
    
    @created.setter
    def created(self, created): # -> None:
        """Sets the created of this Note.

        Creation time (automatically set)

        :param created: The created of this Note.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def modified(self): # -> None:
        """Gets the modified of this Note.

        Last modification time (automatically updated)

        :return: The modified of this Note.
        :rtype: datetime
        """
        ...
    
    @modified.setter
    def modified(self, modified): # -> None:
        """Sets the modified of this Note.

        Last modification time (automatically updated)

        :param modified: The modified of this Note.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def timestamp(self): # -> None:
        """Gets the timestamp of this Note.


        :return: The timestamp of this Note.
        :rtype: datetime
        """
        ...
    
    @timestamp.setter
    def timestamp(self, timestamp): # -> None:
        """Sets the timestamp of this Note.


        :param timestamp: The timestamp of this Note.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def firstname(self): # -> None:
        """Gets the firstname of this Note.


        :return: The firstname of this Note.
        :rtype: str
        """
        ...
    
    @firstname.setter
    def firstname(self, firstname): # -> None:
        """Sets the firstname of this Note.


        :param firstname: The firstname of this Note.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def lastname(self): # -> None:
        """Gets the lastname of this Note.


        :return: The lastname of this Note.
        :rtype: str
        """
        ...
    
    @lastname.setter
    def lastname(self, lastname): # -> None:
        """Sets the lastname of this Note.


        :param lastname: The lastname of this Note.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def text(self): # -> None:
        """Gets the text of this Note.

        The actual contents of the note

        :return: The text of this Note.
        :rtype: str
        """
        ...
    
    @text.setter
    def text(self, text): # -> None:
        """Sets the text of this Note.

        The actual contents of the note

        :param text: The text of this Note.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def user(self): # -> None:
        """Gets the user of this Note.

        Database ID of a user

        :return: The user of this Note.
        :rtype: str
        """
        ...
    
    @user.setter
    def user(self, user): # -> None:
        """Sets the user of this Note.

        Database ID of a user

        :param user: The user of this Note.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def avatar(self): # -> None:
        """Gets the avatar of this Note.

        Last modification time (automatically updated)

        :return: The avatar of this Note.
        :rtype: str
        """
        ...
    
    @avatar.setter
    def avatar(self, avatar): # -> None:
        """Sets the avatar of this Note.

        Last modification time (automatically updated)

        :param avatar: The avatar of this Note.  # noqa: E501
        :type: str
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


