"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class PremadeJobsBatchJobOutputInflatedJobs:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, id=..., origin=..., jobs=..., state=..., created=..., modified=...) -> None:
        """PremadeJobsBatchJobOutputInflatedJobs - a model defined in Swagger"""
        ...
    
    @property
    def id(self): # -> None:
        """Gets the id of this PremadeJobsBatchJobOutputInflatedJobs.


        :return: The id of this PremadeJobsBatchJobOutputInflatedJobs.
        :rtype: str
        """
        ...
    
    @id.setter
    def id(self, id): # -> None:
        """Sets the id of this PremadeJobsBatchJobOutputInflatedJobs.


        :param id: The id of this PremadeJobsBatchJobOutputInflatedJobs.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def origin(self): # -> None:
        """Gets the origin of this PremadeJobsBatchJobOutputInflatedJobs.


        :return: The origin of this PremadeJobsBatchJobOutputInflatedJobs.
        :rtype: Origin
        """
        ...
    
    @origin.setter
    def origin(self, origin): # -> None:
        """Sets the origin of this PremadeJobsBatchJobOutputInflatedJobs.


        :param origin: The origin of this PremadeJobsBatchJobOutputInflatedJobs.  # noqa: E501
        :type: Origin
        """
        ...
    
    @property
    def jobs(self): # -> None:
        """Gets the jobs of this PremadeJobsBatchJobOutputInflatedJobs.


        :return: The jobs of this PremadeJobsBatchJobOutputInflatedJobs.
        :rtype: list[Job]
        """
        ...
    
    @jobs.setter
    def jobs(self, jobs): # -> None:
        """Sets the jobs of this PremadeJobsBatchJobOutputInflatedJobs.


        :param jobs: The jobs of this PremadeJobsBatchJobOutputInflatedJobs.  # noqa: E501
        :type: list[Job]
        """
        ...
    
    @property
    def state(self): # -> None:
        """Gets the state of this PremadeJobsBatchJobOutputInflatedJobs.


        :return: The state of this PremadeJobsBatchJobOutputInflatedJobs.
        :rtype: JobState
        """
        ...
    
    @state.setter
    def state(self, state): # -> None:
        """Sets the state of this PremadeJobsBatchJobOutputInflatedJobs.


        :param state: The state of this PremadeJobsBatchJobOutputInflatedJobs.  # noqa: E501
        :type: JobState
        """
        ...
    
    @property
    def created(self): # -> None:
        """Gets the created of this PremadeJobsBatchJobOutputInflatedJobs.


        :return: The created of this PremadeJobsBatchJobOutputInflatedJobs.
        :rtype: datetime
        """
        ...
    
    @created.setter
    def created(self, created): # -> None:
        """Sets the created of this PremadeJobsBatchJobOutputInflatedJobs.


        :param created: The created of this PremadeJobsBatchJobOutputInflatedJobs.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def modified(self): # -> None:
        """Gets the modified of this PremadeJobsBatchJobOutputInflatedJobs.


        :return: The modified of this PremadeJobsBatchJobOutputInflatedJobs.
        :rtype: datetime
        """
        ...
    
    @modified.setter
    def modified(self, modified): # -> None:
        """Sets the modified of this PremadeJobsBatchJobOutputInflatedJobs.


        :param modified: The modified of this PremadeJobsBatchJobOutputInflatedJobs.  # noqa: E501
        :type: datetime
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


