"""
This type stub file was generated by pyright.
"""

import enum

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class ProjectShareLevel(str, enum.Enum):
    HIGH_LEVEL = ...
    FULL_RO_ACCESS = ...
    def __str__(self) -> str:
        ...
    


