"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class RoleOutput:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, id=..., label=..., default_flywheel_role=..., actions=..., in_use=...) -> None:
        """RoleOutput - a model defined in Swagger"""
        ...
    
    @property
    def id(self): # -> None:
        """Gets the id of this RoleOutput.


        :return: The id of this RoleOutput.
        :rtype: str
        """
        ...
    
    @id.setter
    def id(self, id): # -> None:
        """Sets the id of this RoleOutput.


        :param id: The id of this RoleOutput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def label(self): # -> None:
        """Gets the label of this RoleOutput.


        :return: The label of this RoleOutput.
        :rtype: str
        """
        ...
    
    @label.setter
    def label(self, label): # -> None:
        """Sets the label of this RoleOutput.


        :param label: The label of this RoleOutput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def default_flywheel_role(self): # -> None:
        """Gets the default_flywheel_role of this RoleOutput.


        :return: The default_flywheel_role of this RoleOutput.
        :rtype: DefaultFlywheelRole
        """
        ...
    
    @default_flywheel_role.setter
    def default_flywheel_role(self, default_flywheel_role): # -> None:
        """Sets the default_flywheel_role of this RoleOutput.


        :param default_flywheel_role: The default_flywheel_role of this RoleOutput.  # noqa: E501
        :type: DefaultFlywheelRole
        """
        ...
    
    @property
    def actions(self): # -> None:
        """Gets the actions of this RoleOutput.


        :return: The actions of this RoleOutput.
        :rtype: list[union[Action,DeprecatedAction]]
        """
        ...
    
    @actions.setter
    def actions(self, actions): # -> None:
        """Sets the actions of this RoleOutput.


        :param actions: The actions of this RoleOutput.  # noqa: E501
        :type: list[union[Action,DeprecatedAction]]
        """
        ...
    
    @property
    def in_use(self): # -> None:
        """Gets the in_use of this RoleOutput.


        :return: The in_use of this RoleOutput.
        :rtype: bool
        """
        ...
    
    @in_use.setter
    def in_use(self, in_use): # -> None:
        """Sets the in_use of this RoleOutput.


        :param in_use: The in_use of this RoleOutput.  # noqa: E501
        :type: bool
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


