"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class SaveSearchInput:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, label=..., search=..., parent=...) -> None:
        """SaveSearchInput - a model defined in Swagger"""
        ...
    
    @property
    def label(self): # -> None:
        """Gets the label of this SaveSearchInput.


        :return: The label of this SaveSearchInput.
        :rtype: str
        """
        ...
    
    @label.setter
    def label(self, label): # -> None:
        """Sets the label of this SaveSearchInput.


        :param label: The label of this SaveSearchInput.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def search(self): # -> None:
        """Gets the search of this SaveSearchInput.


        :return: The search of this SaveSearchInput.
        :rtype: SearchQuery
        """
        ...
    
    @search.setter
    def search(self, search): # -> None:
        """Sets the search of this SaveSearchInput.


        :param search: The search of this SaveSearchInput.  # noqa: E501
        :type: SearchQuery
        """
        ...
    
    @property
    def parent(self): # -> None:
        """Gets the parent of this SaveSearchInput.


        :return: The parent of this SaveSearchInput.
        :rtype: SaveSearchParent
        """
        ...
    
    @parent.setter
    def parent(self, parent): # -> None:
        """Sets the parent of this SaveSearchInput.


        :param parent: The parent of this SaveSearchInput.  # noqa: E501
        :type: SaveSearchParent
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


