"""
This type stub file was generated by pyright.
"""

from flywheel.models.structured_query import StructuredQuery

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
SearchStructuredSearchQuery = StructuredQuery
