"""
This type stub file was generated by pyright.
"""

from .mixins import FileMixin

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class SearchFileResponse(FileMixin):
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, classification=..., created=..., type=..., name=..., size=..., cvat=...) -> None:
        """SearchFileResponse - a model defined in Swagger"""
        ...
    
    @property
    def classification(self): # -> None:
        """Gets the classification of this SearchFileResponse.


        :return: The classification of this SearchFileResponse.
        :rtype: CommonClassification
        """
        ...
    
    @classification.setter
    def classification(self, classification): # -> None:
        """Sets the classification of this SearchFileResponse.


        :param classification: The classification of this SearchFileResponse.  # noqa: E501
        :type: CommonClassification
        """
        ...
    
    @property
    def created(self): # -> None:
        """Gets the created of this SearchFileResponse.

        Creation time (automatically set)

        :return: The created of this SearchFileResponse.
        :rtype: datetime
        """
        ...
    
    @created.setter
    def created(self, created): # -> None:
        """Sets the created of this SearchFileResponse.

        Creation time (automatically set)

        :param created: The created of this SearchFileResponse.  # noqa: E501
        :type: datetime
        """
        ...
    
    @property
    def type(self): # -> None:
        """Gets the type of this SearchFileResponse.

        A descriptive file type (e.g. dicom, image, document, ...)

        :return: The type of this SearchFileResponse.
        :rtype: str
        """
        ...
    
    @type.setter
    def type(self, type): # -> None:
        """Sets the type of this SearchFileResponse.

        A descriptive file type (e.g. dicom, image, document, ...)

        :param type: The type of this SearchFileResponse.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def name(self): # -> None:
        """Gets the name of this SearchFileResponse.

        The name of the file on disk

        :return: The name of this SearchFileResponse.
        :rtype: str
        """
        ...
    
    @name.setter
    def name(self, name): # -> None:
        """Sets the name of this SearchFileResponse.

        The name of the file on disk

        :param name: The name of this SearchFileResponse.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def size(self): # -> None:
        """Gets the size of this SearchFileResponse.

        Size of the file, in bytes

        :return: The size of this SearchFileResponse.
        :rtype: int
        """
        ...
    
    @size.setter
    def size(self, size): # -> None:
        """Sets the size of this SearchFileResponse.

        Size of the file, in bytes

        :param size: The size of this SearchFileResponse.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def cvat(self): # -> None:
        """Gets the cvat of this SearchFileResponse.


        :return: The cvat of this SearchFileResponse.
        :rtype: CVATInfo
        """
        ...
    
    @cvat.setter
    def cvat(self, cvat): # -> None:
        """Sets the cvat of this SearchFileResponse.


        :param cvat: The cvat of this SearchFileResponse.  # noqa: E501
        :type: CVATInfo
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


