"""
This type stub file was generated by pyright.
"""

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
class ServerState:
    swagger_types = ...
    attribute_map = ...
    rattribute_map = ...
    def __init__(self, active_user=..., server_url=..., server_options_id=..., state=..., progress=..., progress_url=...) -> None:
        """ServerState - a model defined in Swagger"""
        ...
    
    @property
    def active_user(self): # -> None:
        """Gets the active_user of this ServerState.


        :return: The active_user of this ServerState.
        :rtype: Origin
        """
        ...
    
    @active_user.setter
    def active_user(self, active_user): # -> None:
        """Sets the active_user of this ServerState.


        :param active_user: The active_user of this ServerState.  # noqa: E501
        :type: Origin
        """
        ...
    
    @property
    def server_url(self): # -> None:
        """Gets the server_url of this ServerState.


        :return: The server_url of this ServerState.
        :rtype: str
        """
        ...
    
    @server_url.setter
    def server_url(self, server_url): # -> None:
        """Sets the server_url of this ServerState.


        :param server_url: The server_url of this ServerState.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def server_options_id(self): # -> None:
        """Gets the server_options_id of this ServerState.


        :return: The server_options_id of this ServerState.
        :rtype: str
        """
        ...
    
    @server_options_id.setter
    def server_options_id(self, server_options_id): # -> None:
        """Sets the server_options_id of this ServerState.


        :param server_options_id: The server_options_id of this ServerState.  # noqa: E501
        :type: str
        """
        ...
    
    @property
    def state(self): # -> None:
        """Gets the state of this ServerState.


        :return: The state of this ServerState.
        :rtype: State
        """
        ...
    
    @state.setter
    def state(self, state): # -> None:
        """Sets the state of this ServerState.


        :param state: The state of this ServerState.  # noqa: E501
        :type: State
        """
        ...
    
    @property
    def progress(self): # -> None:
        """Gets the progress of this ServerState.


        :return: The progress of this ServerState.
        :rtype: int
        """
        ...
    
    @progress.setter
    def progress(self, progress): # -> None:
        """Sets the progress of this ServerState.


        :param progress: The progress of this ServerState.  # noqa: E501
        :type: int
        """
        ...
    
    @property
    def progress_url(self): # -> None:
        """Gets the progress_url of this ServerState.


        :return: The progress_url of this ServerState.
        :rtype: str
        """
        ...
    
    @progress_url.setter
    def progress_url(self, progress_url): # -> None:
        """Sets the progress_url of this ServerState.


        :param progress_url: The progress_url of this ServerState.  # noqa: E501
        :type: str
        """
        ...
    
    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        ...
    
    def return_value(self): # -> Self:
        """Unwraps return value from model"""
        ...
    
    def to_dict(self): # -> dict[Any, Any]:
        """Returns the model properties as a dict"""
        ...
    
    def to_str(self): # -> str:
        """Returns the string representation of the model"""
        ...
    
    def __repr__(self): # -> str:
        """For `print` and `pprint`"""
        ...
    
    def __eq__(self, other) -> bool:
        """Returns true if both objects are equal"""
        ...
    
    def __ne__(self, other) -> bool:
        """Returns true if both objects are not equal"""
        ...
    
    def __getitem__(self, key): # -> Any:
        """Returns the value of key"""
        ...
    
    def __setitem__(self, key, value): # -> None:
        """Sets the value of key"""
        ...
    
    def __contains__(self, key): # -> bool:
        """Checks if the given value is a key in this object"""
        ...
    
    def keys(self): # -> dict_keys[str, str]:
        """Returns the list of json properties in the object"""
        ...
    
    def values(self): # -> Generator[Any, Any, None]:
        """Returns the list of values in the object"""
        ...
    
    def items(self): # -> Generator[tuple[str, Any], Any, None]:
        """Returns the list of json property to value mapping"""
        ...
    
    def get(self, key, default=...): # -> Any | None:
        """Get the value of the provided json property, or default"""
        ...
    


